task: train_estimator_only
normalize_data: true

device: cuda
dynamics: mujoco_halfcheetah_mix
# Either specify a single dataset_name or a list in dataset_names.
# dataset_name: mujoco/halfcheetah/simple-v0
# Example for multiple datasets (commented out by default):
dataset_names:
  - mujoco/halfcheetah/simple-v0
  - mujoco/halfcheetah/medium-v0
  - mujoco/halfcheetah/expert-v0
train_batch_size: 1
train_batches_per_epoch: 2048
train_epochs: 10
lr: 0.0003
logger: wandb
sigma: 4.0
seed: 0
suffix: default

# model
hidden_depth: 3
hidden_dim: 512



defaults:
 - _self_
 - estimator: random_feature

hydra:
  run:
    dir: ./log/${dynamics}/${estimator.name}_repr/${now:%Y-%m-%d_%H-%M-%S}_s${seed}_${suffix} # wlayer${estimator.w_hidden_activation}_
  job:
    chdir: true