device: cuda
dynamics: minari_halfcheetah_simple-v0
dataset_name: mujoco/halfcheetah/simple-v0
train_batch_size: 1
train_batches_per_epoch: 2048
train_epochs: 10
lr: 0.0003
sigma: 4.0
seed: 0
suffix: default

# model
feature_dim: 1024
hidden_depth: 3
hidden_dim: 512


defaults:
 - _self_
 - estimator: random_feature

hydra:
  run:
    dir: ./log/${dynamics}/${estimator.name}/${now:%Y-%m-%d_%H-%M-%S}_s${seed}_${suffix} # wlayer${estimator.w_hidden_activation}_
  job:
    chdir: true